name: Create Comment on Pull Request
on:
  pull_request:
    branches:
      - master
jobs:
  createCommentOnPullRequest:
    if: github.event.pull_request.author_association == 'OWNER'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # For debugging purposes. Remove this in production.
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Create comment
        uses: ./
        id: couc
        with:
          issue-number: ${{ github.event.number }}
          upsert: true
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown**
            - Created by [create-or-update-comment][1]

            [1]: https://github.com/peter-evans/create-or-update-comment
          reaction-type: '+1'

      - name: Check outputs
        run: |
          echo "Comment ID - ${{ steps.couc.outputs.comment-id }}"
